name: Test

permissions:
  actions: read
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout database repo
        uses: actions/checkout@v4
        with:
          repository: kontractors/contraman-database  # Replace with actual repo
          ref: main
          path: ./database
          token: ${{ secrets.PAT }}  # Use PAT if private repo

      - name: Start database with Docker Compose
        run: |
          cd database
          docker compose up -d
          # Wait for database to be ready
          timeout 60s bash -c 'until pg_isready -h localhost -p 5432; do sleep 2; done'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: npm run test || echo "No tests configured"

      - name: Stop database
        if: always()
        run: |
          cd database
          docker compose down